---
- name: Copy disable-thp.service to systemd
  copy:
    src: disable-thp.service
    dest: /etc/systemd/system/disable-thp.service
    owner: root
    group: root
    mode: "0644"

- name: Enable and start disable-thp.service
  systemd:
    name: disable-thp.service
    enabled: yes
    state: started
    daemon_reload: yes

- name: Set vm.overcommit_memory=1
  sysctl:
    name: vm.overcommit_memory
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
  when: key_db_sysctl_overcommit